version: "3.8"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://app:not-for-production@postgres:5432/app
      GRAPHQL_INTROSPECTION_ENABLED: "true"
    ports:
      - 4000:4000
      - 5555:5555
    volumes:
      - ./backend/:/app/backend/

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app/frontend/

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: not-for-production
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
